# trimmed 2026 — GnuPG 2.2+ defaults do the heavy lifting
default-key D434B948455AC3C0BBB2BFB2F68AEAEA29DB923E
keyid-format 0xlong
with-fingerprint
no-emit-version
no-comments
ask-cert-level
cert-digest-algo SHA512
