#!/bin/bash

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --widthtype percent --width 10 --transparent true --tint 0x000000 --height 16 &

xsetroot -solid midnightblue

redshift-gtk &
caffeine-indicator &
nautilus --no-desktop --no-default-window &

dropbox start &
