#!/usr/bin/env bash

# Originally from: https://gist.github.com/BaseCase/c45299e4f8474119881d708a4b728fbf
# Blog Post: https://medium.com/adorableio/simple-note-taking-with-fzf-and-vim-2a647a39cfa
# WayBack: https://archive.fo/nhCW0
# Archive.today: https://web.archive.org/web/20190305220348/https://medium.com/adorableio/simple-note-taking-with-fzf-and-vim-2a647a39cfa

set -e

main() {
  previous_file="$1"
  file_to_edit=`select_file $previous_file`

  if [ -n "$file_to_edit" ] ; then
    "$EDITOR" "$file_to_edit"
    main "$file_to_edit"
  fi
}

select_file() {
    # From https://pastebin.com/gKnT9aVr as per https://medium.com/@joni.herttuainen/hi-this-thing-was-awesome-i-hate-using-mouse-or-guis-and-i-like-my-life-in-the-shell-6d963b2faffc
    given_file="$1"
    output=`fzf --preview="bat --color always --pager never --style=numbers {}" --preview-window=right:70%:wrap --print-query --query="$given_file"`
    if [ $? -eq 1 ] ; then
        echo "$output"
    else
        echo "$output" | tail -n 1
    fi
}

main ""
