#!/bin/sh
echo STYLES
echo
echo -e "\e[1mbold\e[0m"
echo -e "\e[3mitalic\e[0m"
echo -e "\e[3m\e[1mbold italic\e[0m"
echo -e "\e[4munderline\e[0m"
echo -e "\e[9mstrikethrough\e[0m"
echo
echo THEME
echo
echo -e "\e[90mbright \e[30mblack\e[0m"
echo -e "\e[91mbright \e[31mred\e[0m"
echo -e "\e[92mbright \e[32mgreen\e[0m"
echo -e "\e[93mbright \e[33myellow\e[0m"
echo -e "\e[94mbright \e[34mblue\e[0m"
echo -e "\e[95mbright \e[35mpurple\e[0m"
echo -e "\e[96mbright \e[36mcyan\e[0m"
echo -e "\e[97mbright \e[37mwhite\e[0m"


echo TRUE COLOR
awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
    s="/\\";
    for (colnum = 0; colnum<term_cols; colnum++) {
        r = 255-(colnum*255/term_cols);
        g = (colnum*510/term_cols);
        b = (colnum*255/term_cols);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum%2+1,1);
    }
    printf "\n";
}'



echo -e "\e[1mbold\e[22m"
echo -e "\e[2mdim\e[22m"
echo -e "\e[3mitalic\e[23m"
echo -e "\e[4munderline\e[24m"
echo -e "\e[4:1mthis is also underline (new in 0.52)\e[4:0m"
echo -e "\e[21mdouble underline (new in 0.52)\e[24m"
echo -e "\e[4:2mthis is also double underline (new in 0.52)\e[4:0m"
echo -e "\e[4:3mcurly underline (new in 0.52)\e[4:0m"
echo -e "\e[5mblink (new in 0.52)\e[25m"
echo -e "\e[7mreverse\e[27m"
echo -e "\e[8minvisible\e[28m <- invisible (but copy-pasteable)"
echo -e "\e[9mstrikethrough\e[29m"
echo -e "\e[53moverline (new in 0.52)\e[55m"

echo -e "\e[38:5:42m256-color, de jure standard (ITU-T T.416)\e[39m"
echo -e "\e[38;5;42m256-color, de facto standard (commonly used)\e[39m"
echo -e "\e[38:2::240:143:104mtruecolor, de jure standard (ITU-T T.416) (new in 0.52)\e[39m"
echo -e "\e[38:2:240:143:104mtruecolor, rarely used incorrect format (might be removed at some point)\e[39m"
echo -e "\e[38;2;240;143;104mtruecolor, de facto standard (commonly used)\e[39m"

echo -e "\e[46mcyan background\e[49m"
echo -e "\e[106mbright cyan background\e[49m"
echo -e "\e[48:5:42m256-color background, de jure standard (ITU-T T.416)\e[49m"
echo -e "\e[48;5;42m256-color background, de facto standard (commonly used)\e[49m"
echo -e "\e[48:2::240:143:104mtruecolor background, de jure standard (ITU-T T.416) (new in 0.52)\e[49m"
echo -e "\e[48:2:240:143:104mtruecolor background, rarely used incorrect format (might be removed at some point)\e[49m"
echo -e "\e[48;2;240;143;104mtruecolor background, de facto standard (commonly used)\e[49m"

echo -e "\e[21m\e[58:5:42m256-color underline (new in 0.52)\e[59m\e[24m"
echo -e "\e[21m\e[58;5;42m256-color underline (new in 0.52)\e[59m\e[24m"
echo -e "\e[4:3m\e[58:2::240:143:104mtruecolor underline (new in 0.52) (*)\e[59m\e[4:0m"
echo -e "\e[4:3m\e[58:2:240:143:104mtruecolor underline (new in 0.52) (might be removed at some point) (*)\e[59m\e[4:0m"
echo -e "\e[4:3m\e[58;2;240;143;104mtruecolor underline (new in 0.52) (*)\e[59m\e[4:0m"

